/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminOP;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.mycompany.footballstadiumticketsystem.DataService;
import com.mycompany.footballstadiumticketsystem.model.MatchFootball;
import com.mycompany.footballstadiumticketsystem.model.Services;
import com.mycompany.footballstadiumticketsystem.model.Stadiums;
import com.mycompany.footballstadiumticketsystem.model.Teams;
import com.mycompany.footballstadiumticketsystem.model.Ticket;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class FootballView extends javax.swing.JFrame {

    /**
     * Creates new form FootballView
     */
    MatchFootball matchFootball = new MatchFootball();

    public FootballView() {
        initComponents();
        ds = new DataService();
        tableemp();
    }
    DataService ds;

    ArrayList<MatchFootball> list;

    public void tableemp() {

        DefaultTableModel model = new DefaultTableModel(new Object[]{"MatchNumber", "Home_TeamId",
            "Home_TeamName", "Away_TeamId", "Away_TeamName",
            "StadiumID", "StadiumName", "DateMatch", "TimeMatch", "City", "NumberSteas", "NumberOfParks"}, 0);
        list = ds.SelectMachFootball();
        Object rowdata[] = new Object[12];
        //System.out.println("size" + list.size());
        for (int i = 0; i < list.size(); i++) {
            rowdata[0] = list.get(i).getMatchNumber();
            rowdata[1] = list.get(i).getHome_Team().getTeamID();
            rowdata[2] = list.get(i).getHome_Team().getTeamName();
            rowdata[3] = list.get(i).getAway_Team().getTeamID();
            rowdata[4] = list.get(i).getAway_Team().getTeamName();
            rowdata[5] = list.get(i).getStadiumID().getStadiumID();
            rowdata[6] = list.get(i).getStadiumID().getStadiumName();
            rowdata[7] = list.get(i).getDateMatch();
            rowdata[8] = list.get(i).getTimeMatch();
            rowdata[9] = list.get(i).getStadiumID().getCity();
            rowdata[10] = list.get(i).getStadiumID().getNumberOfSeates();
            rowdata[11] = list.get(i).getStadiumID().getNumberOfParks();

            model.addRow(rowdata);
        }

        jTable1.setModel(model);
    }

    public void cleanTextBox() {

        btSave.setEnabled(true);
        btUpdate.setEnabled(false);
        btDelete.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        jPanel1 = new javax.swing.JPanel();
        btSave = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 102, 0));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel13.setFont(new java.awt.Font("Lemonada SemiBold", 0, 24)); // NOI18N
        jLabel13.setText("Football Stadium Ticket System");
        jPanel4.add(jLabel13, java.awt.BorderLayout.CENTER);

        jLabel15.setFont(new java.awt.Font("Lemonada SemiBold", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Football View List");
        jPanel4.add(jLabel15, java.awt.BorderLayout.PAGE_START);

        button1.setBackground(new java.awt.Color(255, 51, 0));
        button1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("X");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel4.add(button1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 858, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btSave.setFont(new java.awt.Font("Lemonada SemiBold", 1, 14)); // NOI18N
        btSave.setForeground(new java.awt.Color(255, 102, 0));
        btSave.setText("Add");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, -1));

        btDelete.setFont(new java.awt.Font("Lemonada SemiBold", 1, 14)); // NOI18N
        btDelete.setForeground(new java.awt.Color(255, 102, 0));
        btDelete.setText("Delete");
        btDelete.setEnabled(false);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 210, -1));

        btUpdate.setFont(new java.awt.Font("Lemonada SemiBold", 1, 14)); // NOI18N
        btUpdate.setForeground(new java.awt.Color(255, 102, 0));
        btUpdate.setText("Updata");
        btUpdate.setEnabled(false);
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 180, -1));

        btClear.setFont(new java.awt.Font("Lemonada SemiBold", 1, 14)); // NOI18N
        btClear.setForeground(new java.awt.Color(255, 102, 0));
        btClear.setText("CLear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        jPanel1.add(btClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 144, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(247, 247, 247));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(247, 247, 247));
        jTable1.setSelectionBackground(new java.awt.Color(96, 83, 150));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 858, 430));

        jScrollPane2.setBackground(new java.awt.Color(247, 247, 247));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable2.setGridColor(new java.awt.Color(247, 247, 247));
        jTable2.setSelectionBackground(new java.awt.Color(96, 83, 150));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 858, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed

        if (JOptionPane.showConfirmDialog(null, "Are you sure to close window ", "Warning", JOptionPane.WARNING_MESSAGE) == 0)
            this.dispose();
    }//GEN-LAST:event_button1ActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        FootballMatchNew footballMatchNew = new FootballMatchNew();
        footballMatchNew.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_btSaveActionPerformed

    int MatchNumber;
    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(null, "Do you want to delete");
        if (check == 0) {
            int empId = (MatchNumber);
            ds.deleteMachFootball(empId);
            tableemp();
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        this.matchFootball = new MatchFootball();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        int selectedrow = jTable1.getSelectedRow();
        matchFootball = list.get(selectedrow);
        MatchNumber = list.get(selectedrow).getMatchNumber();
        btDelete.setEnabled(true);
        btUpdate.setEnabled(true);

        btSave.setEnabled(false);

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        FootballMatchNew footballMatchNew = new FootballMatchNew(matchFootball);
        footballMatchNew.setVisible(true);
        dispose();
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
        cleanTextBox();
    }//GEN-LAST:event_btClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        UIManager.setLookAndFeel(new FlatMacDarkLaf());

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FootballView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btUpdate;
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
