/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminOP;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.mycompany.footballstadiumticketsystem.DataService;
import com.mycompany.footballstadiumticketsystem.model.Stadiums;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class StadiumOp extends javax.swing.JFrame {

    /**
     * Creates new form StadiumOp
     */
    Stadiums jopStadiums;
    DataService ds;

    public StadiumOp() {
        initComponents();
        ds = new DataService();
        tableemp();
        txtNumberParks.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                if (!Character.isDigit(evt.getKeyChar())) {
                    evt.consume();
                }
            }
        });
        txtNumberSeates.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                if (!Character.isDigit(evt.getKeyChar())) {
                    evt.consume();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btSave = new javax.swing.JButton();
        txtStadiumId = new javax.swing.JTextField();
        txtStadiumCity = new javax.swing.JTextField();
        txtStadiumName = new javax.swing.JTextField();
        btDelete = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtNumberParks = new javax.swing.JTextField();
        txtNumberSeates = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 102, 0));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Lemonada SemiBold", 0, 24)); // NOI18N
        jLabel13.setText("Football Stadium Ticket System");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 510, 40));

        jLabel15.setFont(new java.awt.Font("Lemonada SemiBold", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Staduim");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 0, 210, -1));

        button1.setBackground(new java.awt.Color(255, 51, 0));
        button1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("X");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel4.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(955, 0, 84, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(247, 247, 247));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), null));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "aistad al'amir turki bin ​​eabd aleaziz ", "alriyad", "20000"},
                {"2", "aistad alriyad ", "alriyad ", "25000"},
                {"3", "aistad aldamaam ", "aldamaam ", "5000"},
                {"4", "aistad alqidia ", "Jadah", "24000"}
            },
            new String [] {
                "Stadium ID", "Stadium Name", "City", "Number Seats"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(247, 247, 247));
        jTable1.setSelectionBackground(new java.awt.Color(255, 102, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 148, 570, 290));

        btSave.setFont(new java.awt.Font("Lemonada SemiBold", 1, 14)); // NOI18N
        btSave.setForeground(new java.awt.Color(255, 102, 0));
        btSave.setText("Add");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 120, -1));

        txtStadiumId.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        txtStadiumId.setForeground(new java.awt.Color(255, 102, 0));
        txtStadiumId.setBorder(null);
        txtStadiumId.setEnabled(false);
        txtStadiumId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtStadiumIdFocusGained(evt);
            }
        });
        getContentPane().add(txtStadiumId, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 164, 290, 35));

        txtStadiumCity.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        txtStadiumCity.setForeground(new java.awt.Color(255, 102, 0));
        txtStadiumCity.setBorder(null);
        txtStadiumCity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtStadiumCityFocusGained(evt);
            }
        });
        getContentPane().add(txtStadiumCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 290, 35));

        txtStadiumName.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        txtStadiumName.setForeground(new java.awt.Color(255, 102, 0));
        txtStadiumName.setBorder(null);
        txtStadiumName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtStadiumNameFocusGained(evt);
            }
        });
        getContentPane().add(txtStadiumName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 290, 35));

        btDelete.setFont(new java.awt.Font("Lemonada SemiBold", 1, 14)); // NOI18N
        btDelete.setForeground(new java.awt.Color(255, 102, 0));
        btDelete.setText("Delete");
        btDelete.setEnabled(false);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 104, -1));

        btUpdate.setFont(new java.awt.Font("Lemonada SemiBold", 1, 14)); // NOI18N
        btUpdate.setForeground(new java.awt.Color(255, 102, 0));
        btUpdate.setText("Update");
        btUpdate.setEnabled(false);
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 120, -1));

        jLabel16.setFont(new java.awt.Font("Lemonada SemiBold", 1, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 0));
        jLabel16.setText("Staduim Name");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 115, -1));

        jLabel17.setFont(new java.awt.Font("Lemonada SemiBold", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 102, 0));
        jLabel17.setText("Staduim Id");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 82, 35));

        jLabel18.setFont(new java.awt.Font("Lemonada SemiBold", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 102, 0));
        jLabel18.setText("City");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 90, -1));

        jLabel19.setFont(new java.awt.Font("Lemonada SemiBold", 1, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 102, 0));
        jLabel19.setText("Number Parks");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 90, -1));

        txtNumberParks.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        txtNumberParks.setForeground(new java.awt.Color(255, 102, 0));
        txtNumberParks.setBorder(null);
        txtNumberParks.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumberParksFocusGained(evt);
            }
        });
        getContentPane().add(txtNumberParks, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 80, 35));

        txtNumberSeates.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        txtNumberSeates.setForeground(new java.awt.Color(255, 102, 0));
        txtNumberSeates.setBorder(null);
        txtNumberSeates.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumberSeatesFocusGained(evt);
            }
        });
        getContentPane().add(txtNumberSeates, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 70, 35));

        jLabel20.setFont(new java.awt.Font("Lemonada SemiBold", 1, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 102, 0));
        jLabel20.setText("Number Seats");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 90, -1));

        btClear.setFont(new java.awt.Font("Lemonada SemiBold", 1, 14)); // NOI18N
        btClear.setForeground(new java.awt.Color(255, 102, 0));
        btClear.setText("CLear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        getContentPane().add(btClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  public void tableemp() {
        //new DefaultTableModel(new String[] {"id","name","price","Qty","Total"},0);
        DefaultTableModel model = new DefaultTableModel(new Object[]{"StadiumID",
            "StadiumName ", "City", "NumberSteas", "NumberOfParks"}, 0);
        ArrayList<Stadiums> list = ds.SelectStadiums();
        Object rowdata[] = new Object[5];
        //System.out.println("size" + list.size());
        for (int i = 0; i < list.size(); i++) {
            rowdata[0] = list.get(i).getStadiumID();
            rowdata[1] = list.get(i).getStadiumName();
            rowdata[2] = list.get(i).getCity();
            rowdata[3] = list.get(i).getNumberOfSeates();
            rowdata[4] = list.get(i).getNumberOfParks();
            model.addRow(rowdata);
        }

        jTable1.setModel(model);
    }

    Stadiums stadiums = new Stadiums();

    public void addStadiums() throws SQLException {
        int result = 0;

        if (txtStadiumName.getText().equals("") || txtStadiumCity.equals("") || txtNumberParks.equals("")) {
            JOptionPane.showMessageDialog(this, "Please make sure that none of the fields are blank.", "Entry Error", 1);
        } else {
            stadiums.setStadiumName(txtStadiumName.getText());
            stadiums.setCity(txtStadiumCity.getText());
            stadiums.setNumberOfSeates(Integer.parseInt(txtNumberParks.getText()));
            stadiums.setNumberOfParks(Integer.parseInt(txtNumberParks.getText()));

            if (ds.InsertStadiums(stadiums) == 1) {
                JOptionPane.showMessageDialog(this, "Records inserted successfully.", "Entry Error", 1);
            } else {
                JOptionPane.showMessageDialog(this, "Records insertion failed.", "Entry Error", 1);
            }

            //   con.close();
        }
    }

    public void cleanTextBox() {

        txtStadiumName.setText("");
        txtStadiumCity.setText("");
        txtNumberParks.setText("");
        txtStadiumId.setText("");
        txtNumberSeates.setText("");
        btSave.setEnabled(true);
        btUpdate.setEnabled(false);
        btDelete.setEnabled(false);

    }

    public void updateData() {

        //actionGender().equals("not selected")
        if (txtStadiumName.getText().equals("")
                || txtStadiumCity.equals("") || txtNumberParks.equals("") || txtNumberParks.equals("")) {
            JOptionPane.showMessageDialog(this, "Please make sure that none of the fields are blank.", "Entry Error", 1);
        } else {

            //int id=GetNextValue("persons", "person_id");
            stadiums.setStadiumName(txtStadiumName.getText());
            stadiums.setCity(txtStadiumCity.getText());
            stadiums.setNumberOfSeates(Integer.parseInt(txtNumberSeates.getText()));
            stadiums.setNumberOfParks(Integer.parseInt(txtNumberParks.getText()));

            ds.updateStadiums(Integer.valueOf(txtStadiumId.getText()), stadiums);

        }

    }
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed

        if (JOptionPane.showConfirmDialog(null, "Are you sure to close window ", "Warning", JOptionPane.WARNING_MESSAGE) == 0)
            this.dispose();
    }//GEN-LAST:event_button1ActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
//        loader.show();
        //      login.hide();
        try {

            addStadiums();

            cleanTextBox();
            tableemp();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, " error" + e.getMessage());
        }
    }//GEN-LAST:event_btSaveActionPerformed

    private void txtStadiumIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStadiumIdFocusGained
        // TODO add your handling code here:
        txtStadiumId.setText("");
    }//GEN-LAST:event_txtStadiumIdFocusGained

    private void txtStadiumCityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStadiumCityFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStadiumCityFocusGained

    private void txtStadiumNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStadiumNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStadiumNameFocusGained

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(null, "Do you want to delete");
        if (check == 0) {
            int empId = Integer.valueOf(txtStadiumId.getText());
            ds.deleteStadiums(empId);
            cleanTextBox();
            tableemp();
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        // TODO add your handling code here:
        updateData();

        cleanTextBox();
        tableemp();
    }//GEN-LAST:event_btUpdateActionPerformed

    private void txtNumberParksFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumberParksFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberParksFocusGained

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        this.stadiums = new Stadiums();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        int selectedrow = jTable1.getSelectedRow();
        txtStadiumId.setText(model.getValueAt(selectedrow, 0).toString());
        txtStadiumName.setText(model.getValueAt(selectedrow, 1).toString());
        txtStadiumCity.setText(model.getValueAt(selectedrow, 2).toString());
        txtNumberSeates.setText(model.getValueAt(selectedrow, 3).toString());
        txtNumberParks.setText(model.getValueAt(selectedrow, 4).toString());
        btUpdate.setEnabled(true);
        btDelete.setEnabled(true);
        btSave.setEnabled(false);

    }//GEN-LAST:event_jTable1MouseClicked

    private void txtNumberSeatesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumberSeatesFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberSeatesFocusGained

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
        cleanTextBox();
    }//GEN-LAST:event_btClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        UIManager.setLookAndFeel(new FlatDarculaLaf());

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StadiumOp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btUpdate;
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtNumberParks;
    private javax.swing.JTextField txtNumberSeates;
    private javax.swing.JTextField txtStadiumCity;
    private javax.swing.JTextField txtStadiumId;
    private javax.swing.JTextField txtStadiumName;
    // End of variables declaration//GEN-END:variables
}
