/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminOP;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.mycompany.footballstadiumticketsystem.DataService;
import com.mycompany.footballstadiumticketsystem.model.Stadiums;
import com.mycompany.footballstadiumticketsystem.model.Teams;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class TeamsOp extends javax.swing.JFrame {

    /**
     * Creates new form TeamsOp
     */
    Stadiums jopStadiums;

    public TeamsOp() {
        initComponents();
        ds = new DataService();
        tableemp();
    }
    DataService ds;
    ArrayList<Teams> list;

    public void tableemp() {
        //new DefaultTableModel(new String[] {"id","name","price","Qty","Total"},0);
        DefaultTableModel model = new DefaultTableModel(new Object[]{"TeamID", "TeamName",
            "DateOfEstablishment", "Loaction"}, 0);
        list = ds.SelectTeams();
        Object rowdata[] = new Object[4];
        //System.out.println("size" + list.size());
        for (int i = 0; i < list.size(); i++) {
            rowdata[0] = list.get(i).getTeamID();
            rowdata[1] = list.get(i).getTeamName();
            rowdata[2] = list.get(i).getDateOfEstablishment();
            rowdata[3] = list.get(i).getLoaction();

            model.addRow(rowdata);
        }

        jTable1.setModel(model);
    }

    Teams teams = new Teams();

    public void addTeam() throws SQLException {
        int result = 0;

        if (txtTeamName.getText().equals("") || txtLocation.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please make sure that none of the fields are blank.", "Entry Error", 1);
        } else {
            teams.setTeamName(txtTeamName.getText());

            teams.setDateOfEstablishment(new java.sql.Date(dtTeam.getDate().getTime()));
            teams.setLoaction(txtLocation.getText());

            if (ds.InsertTeams(teams) == 1) {
                JOptionPane.showMessageDialog(this, "Records inserted successfully.", "Entry Error", 1);
            } else {
                JOptionPane.showMessageDialog(this, "Records insertion failed.", "Entry Error", 1);
            }

            //   con.close();
        }
    }

    public void cleanTextBox() {

        txtTeamName.setText("");
        txtTeamId.setText("");
        txtLocation.setText("");
        dtTeam.setToolTipText("");
        btSave.setEnabled(true);
        btUpdate.setEnabled(false);
        btDelete.setEnabled(false);
        btSaveRow.setEnabled(false);

    }

    public void updateData() {

        //actionGender().equals("not selected")
        if (txtTeamId.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please make sure that none of the fields are blank.", "Entry Error", 1);
        } else {

            teams.setTeamName(txtTeamName.getText());
            teams.setLoaction(txtLocation.getText());
            teams.setDateOfEstablishment(new java.sql.Date(dtTeam.getDate().getTime()));

            ds.updateTeams(Integer.valueOf(txtTeamId.getText()), teams);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        txtDateOfEstablishment = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtTeamId = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTeamName = new javax.swing.JTextField();
        btSave = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        dtTeam = new com.toedter.calendar.JDateChooser();
        tx = new javax.swing.JLabel();
        btClear = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        btSaveRow = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        txtDateOfEstablishment.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        txtDateOfEstablishment.setForeground(new java.awt.Color(255, 102, 0));
        txtDateOfEstablishment.setBorder(null);
        txtDateOfEstablishment.setEnabled(false);
        txtDateOfEstablishment.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDateOfEstablishmentFocusGained(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), null));
        jTable1.setFont(new java.awt.Font("Lemonada SemiBold", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(247, 247, 247));
        jTable1.setSelectionBackground(new java.awt.Color(255, 102, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 470, 270));

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Lemonada SemiBold", 0, 24)); // NOI18N
        jLabel13.setText("Football Stadium Ticket System");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 510, 40));

        exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 22, -1));

        jLabel15.setFont(new java.awt.Font("Lemonada SemiBold", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Teams");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 210, -1));
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 90, 100));
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 130));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Lemonada SemiBold", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 102, 0));
        jLabel17.setText("Team Id");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 76, -1));

        txtTeamId.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        txtTeamId.setForeground(new java.awt.Color(255, 102, 0));
        txtTeamId.setBorder(null);
        txtTeamId.setEnabled(false);
        txtTeamId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTeamIdFocusGained(evt);
            }
        });
        jPanel3.add(txtTeamId, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 6, 350, 35));

        jLabel18.setFont(new java.awt.Font("Lemonada SemiBold", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 102, 0));
        jLabel18.setText("Team Name");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 62, 76, -1));

        txtTeamName.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        txtTeamName.setForeground(new java.awt.Color(255, 102, 0));
        txtTeamName.setBorder(null);
        txtTeamName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTeamNameFocusGained(evt);
            }
        });
        jPanel3.add(txtTeamName, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 53, 350, 35));

        btSave.setFont(new java.awt.Font("Lemonada SemiBold", 1, 14)); // NOI18N
        btSave.setForeground(new java.awt.Color(255, 102, 0));
        btSave.setText("Add");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 111, -1));

        btUpdate.setFont(new java.awt.Font("Lemonada SemiBold", 1, 14)); // NOI18N
        btUpdate.setForeground(new java.awt.Color(255, 102, 0));
        btUpdate.setText("Update");
        btUpdate.setEnabled(false);
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 104, -1));

        btDelete.setFont(new java.awt.Font("Lemonada SemiBold", 1, 14)); // NOI18N
        btDelete.setForeground(new java.awt.Color(255, 102, 0));
        btDelete.setText("Delete");
        btDelete.setEnabled(false);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 104, -1));

        jLabel19.setFont(new java.awt.Font("Lemonada SemiBold", 1, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 102, 0));
        jLabel19.setText(" Loaction");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 109, 76, -1));

        txtLocation.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        txtLocation.setForeground(new java.awt.Color(255, 102, 0));
        txtLocation.setBorder(null);
        txtLocation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLocationFocusGained(evt);
            }
        });
        jPanel3.add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 350, 35));

        dtTeam.setDateFormatString("dd‏/MM‏/y ");
        dtTeam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtTeamMouseClicked(evt);
            }
        });
        jPanel3.add(dtTeam, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 180, 230, 30));

        tx.setFont(new java.awt.Font("Lemonada SemiBold", 1, 10)); // NOI18N
        tx.setForeground(new java.awt.Color(255, 102, 0));
        tx.setText("Date Of Establishment");
        jPanel3.add(tx, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 280, -1));

        btClear.setFont(new java.awt.Font("Lemonada SemiBold", 1, 14)); // NOI18N
        btClear.setForeground(new java.awt.Color(255, 102, 0));
        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        jPanel3.add(btClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 111, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 136, 460, 280));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Data Went Save file");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 190, 24));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Data Read of File");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 110, 24));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 440, 150));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 460, 150));

        jButton3.setText("Open File Text");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 630, 460, 30));

        btSaveRow.setText("Save File Text Row Onlay");
        btSaveRow.setEnabled(false);
        btSaveRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveRowActionPerformed(evt);
            }
        });
        getContentPane().add(btSaveRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 440, 30));

        jButton2.setText("Save File Text All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 440, 30));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_exitMousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        //   this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        //  xx = evt.getX();
        // xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void txtTeamIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTeamIdFocusGained
        // TODO add your handling code here:
        txtTeamId.setText("");
    }//GEN-LAST:event_txtTeamIdFocusGained

    private void txtTeamNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTeamNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeamNameFocusGained

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        try {
            addTeam();

            cleanTextBox();
            tableemp();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, " error" + e.getMessage());
        }
    }//GEN-LAST:event_btSaveActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        updateData();

        cleanTextBox();
        tableemp();    }//GEN-LAST:event_btUpdateActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(null, "Do you want to delete");
        if (check == 0) {
            int empId = Integer.valueOf(txtTeamId.getText());
            ds.deleteTeams(empId);
            cleanTextBox();
            tableemp();
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        this.teams = new Teams();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Date siDate = null;
        int selectedrow = jTable1.getSelectedRow();
        txtTeamId.setText(model.getValueAt(selectedrow, 0).toString());
        txtTeamName.setText(model.getValueAt(selectedrow, 1).toString());
        try {
            if (model.getValueAt(selectedrow, 2).toString() == null) {

            } else {
                String dateValue = (model.getValueAt(selectedrow, 2).toString());
// Your column Name
                if (dateValue.equals("")) {

                } else {
                    java.util.Date date = new SimpleDateFormat("dd-MM-yyyy").parse(dateValue);

                  
                    dtTeam.setDate(date);
                }
            }
        } catch (ParseException ex) {
            Logger.getLogger(TeamsOp.class.getName()).log(Level.SEVERE, null, ex);
        }
        // dtTeam.setDate(Date.valueOf(siDate));
        txtLocation.setText(model.getValueAt(selectedrow, 3).toString());
        btUpdate.setEnabled(true);
        btDelete.setEnabled(true);
        btSave.setEnabled(false);
        btSaveRow.setEnabled(true);

    }//GEN-LAST:event_jTable1MouseClicked

    private void txtLocationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLocationFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocationFocusGained

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
        cleanTextBox();
    }//GEN-LAST:event_btClearActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        doOpenFile();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    private void doOpenFile() {
        k = new JFileChooser();
        int result = k.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            Path path = k.getSelectedFile().toPath();

            try {
                String contentString = "";

                for (String s : Files.readAllLines(path, StandardCharsets.UTF_8)) {
                    contentString += s;
                }

                jTextArea2.setText(contentString);

            } catch (IOException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
    }
    JFileChooser k;

    private void doSaveFile() {
        int result;
        k = new JFileChooser();
        result = k.showSaveDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            // We'll be making a mytmp.txt file, write in there, then move it to
            // the selected
            // file. This takes care of clearing that file, should there be
            // content in it.
            File targetFile = k.getSelectedFile();

            try {
                if (!targetFile.exists()) {
                    targetFile.createNewFile();
                }

                FileWriter fw = new FileWriter(targetFile + ".txt");

                fw.write(jTextArea1.getText());
                fw.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
    private void btSaveRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveRowActionPerformed
        try {
            jTextArea1.setLineWrap(true);
            jTextArea1.setText(" Football Stadium Ticket System ");
            jTextArea1.append("\n");
            jTextArea1.setText(jTextArea1.getText() + " " + "Team Id :  " + txtTeamId.getText());
            jTextArea1.append("\n");
            jTextArea1.setText(jTextArea1.getText() + " " + "Team Name :  " + txtTeamName.getText());
            jTextArea1.append("\n");
            jTextArea1.append("\n");
            jTextArea1.setText(jTextArea1.getText() + " " + " Date Of Establishment :  " + txtDateOfEstablishment.getText());
            jTextArea1.append("\n");
            jTextArea1.append("\n");
            jTextArea1.setText(jTextArea1.getText() + " " + " Location :  " + txtLocation.getText());
            jTextArea1.append("\n");
            jTextArea1.append("\n");

            FileOutputStream fos = null;
            String fileData = jTextArea1.getText();
            fos = new FileOutputStream(txtTeamName.getText() + ".txt");
            fos.write(fileData.getBytes());
            fos.flush();
            fos.close();
            FileWriter myWriter = null;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TeamsOp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TeamsOp.class.getName()).log(Level.SEVERE, null, ex);
        }
        doSaveFile();

        // TODO add your handling code here:
    }//GEN-LAST:event_btSaveRowActionPerformed

    private void txtDateOfEstablishmentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateOfEstablishmentFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOfEstablishmentFocusGained

    private void dtTeamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtTeamMouseClicked
        txtDateOfEstablishment.setText(dtTeam.getDate().getTime() + "");
    }//GEN-LAST:event_dtTeamMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            jTextArea1.setLineWrap(true);
            for (int i = 0; i < list.size(); i++) {

                jTextArea1.setText(jTextArea1.getText() + " Football Stadium Ticket System ");
                jTextArea1.append("\n");
                jTextArea1.setText(jTextArea1.getText() + " " + "Team Id :  " + list.get(i).getTeamID());
                jTextArea1.append("\n");
                jTextArea1.setText(jTextArea1.getText() + " " + "Team Name :  " + list.get(i).getTeamName());
                jTextArea1.append("\n");
                jTextArea1.append("\n");
                jTextArea1.setText(jTextArea1.getText() + " " + " Date Of Establishment :  " + list.get(i).getDateOfEstablishment());
                jTextArea1.append("\n");
                jTextArea1.append("\n");
                jTextArea1.setText(jTextArea1.getText() + " " + " Location :  " + list.get(i).getLoaction());
                jTextArea1.append("\n");
                jTextArea1.append("\n");
            }
            FileOutputStream fos = null;
            String fileData = jTextArea1.getText();
            fos = new FileOutputStream(txtTeamName.getText() + ".txt");
            fos.write(fileData.getBytes());
            fos.flush();
            fos.close();
            FileWriter myWriter = null;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TeamsOp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TeamsOp.class.getName()).log(Level.SEVERE, null, ex);
        }
        doSaveFile();

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        UIManager.setLookAndFeel(new FlatMacDarkLaf());
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeamsOp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btSaveRow;
    private javax.swing.JButton btUpdate;
    private com.toedter.calendar.JDateChooser dtTeam;
    private javax.swing.JLabel exit;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel tx;
    private javax.swing.JTextField txtDateOfEstablishment;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtTeamId;
    private javax.swing.JTextField txtTeamName;
    // End of variables declaration//GEN-END:variables
}
